export { IAnswer } from "./Answer";
export { IQuestion } from "./Question";
export { IUserAnswer } from "./UserAnswer";
export { IResponse } from "./Response";
export { IResult } from "./Result";
export { IQuiz } from "./Quiz";
export { IControl } from "./Control";
export { IValidation } from "./Validation";
export { IValidControl } from "./ValidControl";
